<a href="https://colab.research.google.com/github/wozzin/AI_ML/blob/main/Softmax_define.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 소프트맥스

- 세 개 이상 입력 값을 다루기 위함(다중분류)
- 다항 로지스틱스

> \\( { y }_{ k }=\frac { exp({ a }_{ k }) }{ \sum _{ i=1 }^{ n }{ exp({ a }_{ i }) }  }  \\)


In [4]:
import numpy as np


In [5]:
score = [ -1, 0.5 , 1.0 , 1.5]

prop = []
sum = 0
for s in score:
  prop.append(np.exp(s))
  sum += np.exp(s)

prop / sum

array([0.039915  , 0.17888661, 0.29493416, 0.48626423])

In [6]:
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)
print(exp_a)

sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)
print( np.sum(y) )

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]
1.0


In [9]:
def softmax(a):
  exp_a = np.exp(a)         # 지수함수
  sum_exp_a = np.sum(exp_a) # 지수의 합
  y = exp_a / sum_exp_a     # 확률
  return y


a = np.array([0.3, 2.9, 4.0])
y = softmax(a)

In [8]:
# 오버플로우 대책
def softmax(a):
  c = np.max(a)
  exp_a = np.exp(a - c)         # 지수함수
  y = exp_a / np.sum(exp_a) # 지수의 합, 확률
  return y


a = np.array([1010, 1000, 990])
y = softmax(a)
print(y)
print( np.sum(y) )

[9.99954600e-01 4.53978686e-05 2.06106005e-09]
1.0
